/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GraphBar: typeof import('./components/GraphBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionPrimary: typeof import('./components/Section/SectionPrimary.vue')['default']
    SectionSecundary: typeof import('./components/Section/SectionSecundary.vue')['default']
    TableApi: typeof import('./components/TableApi.vue')['default']
  }
}
